# Generated by Django 2.2.7 on 2019-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191119_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
