# Generated by Django 2.2.7 on 2019-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20191120_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Item', max_length=50)),
                ('description', models.CharField(default='Default Item', max_length=500)),
                ('players', models.ManyToManyField(to='adventure.Player')),
                ('rooms', models.ManyToManyField(to='adventure.Room')),
            ],
        ),
    ]
