# Generated by Django 2.2.7 on 2019-11-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='players',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rooms',
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.ManyToManyField(to='adventure.Item'),
        ),
        migrations.AddField(
            model_name='room',
            name='item',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='adventure.Item'),
            preserve_default=False,
        ),
    ]
