# Generated by Django 2.2.7 on 2019-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20191121_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='char_class',
            field=models.CharField(default='warrior', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='sprite',
            field=models.CharField(default='boy', max_length=50),
        ),
    ]
