# Generated by Django 2.2.7 on 2019-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20191121_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='item',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE, to='adventure.Item'),
        ),
    ]
