# Generated by Django 2.2.7 on 2019-11-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20191121_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gold_count',
            field=models.IntegerField(default=0),
        ),
    ]
